### ISSUE TITLE
Can't get it work on Windows 10

### ISSUE THREAD

**Issue by Neurotoxin001** [jibbex/jib-FFmpeg#6]
```
D:\temp\jib-FFmpeg-master>yarn start
yarn run v1.22.5
$ electron-forge start
√ Checking your system
√ Locating Application
√ Preparing native dependencies
√ Launching Application

(electron) 'setName function' is deprecated and will be removed. Please use 'name property' instead.
Server listening on port 4480
(node:2700) UnhandledPromiseRejectionWarning: Error: Exited with code 2
    at ChildProcess.<anonymous> (D:\temp\jib-FFmpeg-master\node_modules\cross-unzip\index.js:38:21)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:2700) UnhandledPromiseRejectionWarning: Error: Exited with code 2
    at ChildProcess.<anonymous> (D:\temp\jib-FFmpeg-master\node_modules\cross-unzip\index.js:38:21)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:2700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
all tasks finished
all tasks finished
```

And then nothing happens.

Git-2.31.1-64-bit
node-v14.16.1-x64
yarn-1.22.5
Windows 10 LTSC 1809

**Comment by jibbex** [comment]
I couldn't reproduce the exact error message but was able to observe a weird behavior of react-hot-loader and electron-devtools-installer. you can expect a fix later this day.

**Comment by jibbex** [comment]
I have changed the appropriate sections and hope that it works now. If not, feel free to leave a reply. Thank you.
